from .cardinal              import TestInitCardinal
from .coordonnee            import TestInitCoordonnee
from .deplacement           import TestInitDeplacement
from .direction             import TestInitDirection
from .map                   import TestInitMap
from .point                 import TestInitPoint
from .position              import TestInitPosition
from .rover                 import TestInitRover
from .roverMessagePosition  import TestInitRoverMessagePosition